[workspace]
resolver = "2"
members = ["lzallright", "python"]
exclude = ["fuzz"]

[workspace.package]
# Inherited by the Python package
version = "0.3.0"
authors = ["László Vaskó <1771332+vlaci@users.noreply.github.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.83"
description = "A Python 3.11+ LZO compression library in safe Rust, ported from LZ👌 (lzokay)"
repository = "https://github.com/vlaci/lzallright"
homepage = "https://vlaci.github.io/lzallright"
readme = "README.md"

[workspace.dependencies]
criterion = "0.8"

[workspace.metadata.crane]
name = "lzallright"

[profile.release]
debug = true

[profile.release-lto]
inherits = "release"
opt-level = 3
panic = "abort"
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
incremental = false
codegen-units = 1

[profile.bench]
inherits = "release-lto"
