from array import array
from mmap import mmap
from typing import Union

class LZOError(Exception):
    pass

class EResult:
    LookbehindOverrun = ...
    OutputOverrun = ...
    InputOverrun = ...
    Error = ...
    InputNotConsumed = ...

_BufferType = Union[array[int], bytes, bytearray, memoryview, mmap]

class LZOCompressor:
    def compress(self, data: _BufferType) -> bytes: ...
    @staticmethod
    def decompress(data: _BufferType) -> bytes: ...
